### ISSUE TITLE
dataset_gpt_dict bug?

### ISSUE THREAD

**Issue by JCSTARS** [Alexander-Yao/Multi-MaP#1]
Hi, that's a great work. I just have a question of the code in main.py from line 65-line 76
`   dataset_prompt_dict = {
        "fruit": ["Fruit with a species of", "Fruit with a color of"], 
        "fruit360": ["Fruit with a species of", "Fruit with a color of"],
        "cards": ["Card with number of", "Card with suits of"],
        "CMUface": ["Face with identity of", "Face with emotion of", "Face with glass of", "Face with pose of"]
    } `
`
    dataset_gpt_dict = {
        "fruit": ["apples, oranges, bananas, strawberries, grapes, raspberries, blueberries, cherries, pears, plums, peaches, nectarines, pineapple, kiwi, watermelon, cantaloupe, apricots", "red, yellow, green, orange, purple, blue"],
        "fruit360": ["apples, oranges, bananas, strawberries, grapes, raspberries, blueberries, cherries, pears, plums, peaches, nectarines, pineapple, kiwi, watermelon, cantaloupe, apricots", "red, yellow, green, orange, purple, blue"],
        "cards": ["Card with number of", "Card with suits of"],
        "CMUface": ["1, 2, 3, 4, 5, 6, 7, 8, 9, 10", "happiness, sadness, anger, surprise, fear, disgust, contempt", "positive, fashionable", "smiling, frowning, neutral expression, laughing, raised eyebrows, squinting, pouting, wide-eyed, nodding, tilting head"]
    }`
    
  I understand that in fruit, CMUface dataset, the gpt dict are the reference words provide by gpt, but it's seems that for 'cards' dataset, the gpt dict are the same as the prompt? Should it be like ‘Ace, Queen, three, four..’ and 'Diamond, Spade ..'?

**Comment by Alexander-Yao** [comment]
Hi @JCSTARS, you are absolutely correct. In this case, the gpt_dict for cards should indeed include actual card ranks (e.g., "Ace, Queen, three, four..") and suits (e.g., "Diamond, Spade..").
